const permissionList = [
    {
    "children": [],
    "id": "0159193ce5ab4eff822ad495bc17a39e",
    "inputTime": "2020-03-13 11:37:38",
    "name": "概览",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "INDEX",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "240e6c4d60eb4d18be28a071e1f60ae5",
    "inputTime": "2020-03-13 11:37:38",
    "name": "访客趋势",
    "pid": "0159193ce5ab4eff822ad495bc17a39e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "INDEX_VISIT_CHART",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "9a75cf551251485abbb0eae260fb0595",
    "inputTime": "2020-03-13 11:37:38",
    "name": "常用功能",
    "pid": "0159193ce5ab4eff822ad495bc17a39e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "INDEX_SHORTCUT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "683f80c055ca485eba366625fcc9bee5",
    "inputTime": "2020-03-13 11:37:38",
    "name": "订单查询",
    "pid": "9a75cf551251485abbb0eae260fb0595",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "INDEX_SHORTCUT_ORDER_QUERY",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "8dec7f95eeb24034b4ab3b09a9ec2b30",
    "inputTime": "2020-03-13 11:37:38",
    "name": "客户管理",
    "pid": "9a75cf551251485abbb0eae260fb0595",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "INDEX_SHORTCUT_CUSTOMER_MANAGER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "d8b5134c7b29479190393d71d770f772",
    "inputTime": "2020-03-13 11:37:38",
    "name": "收入/提现",
    "pid": "9a75cf551251485abbb0eae260fb0595",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "INDEX_SHORTCUT_INCOME",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "fe86d18e218e4a42ace8c939a89c905b",
    "inputTime": "2020-03-13 11:37:38",
    "name": "发布商品",
    "pid": "9a75cf551251485abbb0eae260fb0595",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "INDEX_SHORTCUT_NEW_GOODS",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "d9c2254940074c32aedec555339f09f5",
    "inputTime": "2020-03-13 11:37:38",
    "name": "交易趋势",
    "pid": "0159193ce5ab4eff822ad495bc17a39e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "INDEX_DEAL_CHART",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "e4ab65876b454e62976481da28cc2d80",
    "inputTime": "2020-03-13 11:37:38",
    "name": "实时概览",
    "pid": "0159193ce5ab4eff822ad495bc17a39e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "INDEX_BANNER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "33c5c260f7de467fb9b2e86e392317e2",
    "inputTime": "2020-03-13 11:37:38",
    "name": "客户",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "CUSTOMER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "24b3fb0ff58d425588475ad7ea528843",
    "inputTime": "2020-03-13 11:37:38",
    "name": "客户管理",
    "pid": "33c5c260f7de467fb9b2e86e392317e2",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "CUSTOMER_MANAGER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "1adc5d62c1394ec79702be21f7e83124",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "24b3fb0ff58d425588475ad7ea528843",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "CUSTOMER_MANAGER_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "28f23d836e5a4715a348ef30315af54e",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "24b3fb0ff58d425588475ad7ea528843",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "CUSTOMER_MANAGER_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "a862927775a64b7fbb8a95cae67cc73d",
    "inputTime": "2020-03-13 11:37:38",
    "name": "客户标签",
    "pid": "33c5c260f7de467fb9b2e86e392317e2",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "CUSTOMER_LABEL",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "6b135cbe119947bf9fca31593483fe5e",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "a862927775a64b7fbb8a95cae67cc73d",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "CUSTOMER_LABEL_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "a7cc0d7eea884073a34c49a40cc2412c",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "a862927775a64b7fbb8a95cae67cc73d",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "CUSTOMER_LABEL_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "5659e2ff17a04bd498de3f4becc1120e",
    "inputTime": "2020-03-13 11:37:39",
    "name": "设置",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "SET",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "2001b7b7c9f94e9489eac6c461dc1bfa",
    "inputTime": "2020-03-13 11:37:39",
    "name": "通用设置",
    "pid": "5659e2ff17a04bd498de3f4becc1120e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_COMMON",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "1f5f24b55fc849fa82b6763b2440c6de",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "2001b7b7c9f94e9489eac6c461dc1bfa",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_COMMON_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "ffe855cbc7dc4dcf92da4a2a80e4d0b2",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "2001b7b7c9f94e9489eac6c461dc1bfa",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_COMMON_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "4c54c3ff66e841cbbfee0b13b9b9e1c1",
    "inputTime": "2020-03-13 11:37:39",
    "name": "店铺信息",
    "pid": "5659e2ff17a04bd498de3f4becc1120e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_STORE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "3853f9cab46249c589b63eb68faab57e",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "4c54c3ff66e841cbbfee0b13b9b9e1c1",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_STORE_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "80513d7e27db49cd8036a284dd58290b",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "4c54c3ff66e841cbbfee0b13b9b9e1c1",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_STORE_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "9da9a235cc0d46bcb4d6c40c2530924f",
    "inputTime": "2020-03-13 11:37:39",
    "name": "成员管理",
    "pid": "5659e2ff17a04bd498de3f4becc1120e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_USER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "4b584097929c4b55bd7ca0f0e84a9eba",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "9da9a235cc0d46bcb4d6c40c2530924f",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_USER_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "7cfb0a9d97d44dd2b126934434980cf0",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "9da9a235cc0d46bcb4d6c40c2530924f",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_USER_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "daf6c987a42747c0bc564dfbdf27d6f1",
    "inputTime": "2020-03-13 11:37:39",
    "name": "商家地址",
    "pid": "5659e2ff17a04bd498de3f4becc1120e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_ADDRESS",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "4241fee52310459f9190efa367fea2cc",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "daf6c987a42747c0bc564dfbdf27d6f1",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_ADDRESS_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "c4fc6922242841ce8b739eee14bb2629",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "daf6c987a42747c0bc564dfbdf27d6f1",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_ADDRESS_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "f30ea00aa42644a3a19d09958c4b1468",
    "inputTime": "2020-03-13 11:37:39",
    "name": "角色管理",
    "pid": "5659e2ff17a04bd498de3f4becc1120e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_ROLE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "7bff60719dd740fe8039ccb00437f6b5",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "f30ea00aa42644a3a19d09958c4b1468",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_ROLE_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "a3f6174a258d47c3961b21973c4328ce",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "f30ea00aa42644a3a19d09958c4b1468",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_ROLE_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "f3a9cd2be46344cd8d54eb3d52ca7b45",
    "inputTime": "2020-03-13 11:37:39",
    "name": "核销员",
    "pid": "5659e2ff17a04bd498de3f4becc1120e",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_CHECKER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "461cf1033f1341cbad768692b130e634",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "f3a9cd2be46344cd8d54eb3d52ca7b45",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SET_CHECKER_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "68e3342c1ad242ac8338578784acf108",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "f3a9cd2be46344cd8d54eb3d52ca7b45",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SET_CHECKER_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "98d56736c32d4ed4a20cb93b1335e7bb",
    "inputTime": "2020-03-13 11:37:39",
    "name": "资产",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "BALANCE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "14e39ab6ebd54fe88ab46ebf567f728c",
    "inputTime": "2020-03-13 11:37:39",
    "name": "账单明细",
    "pid": "98d56736c32d4ed4a20cb93b1335e7bb",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "BALANCE_BILL",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "14ac7da22d624375afabdc0d387d2d12",
    "inputTime": "2020-04-10 15:11:58",
    "name": "查看",
    "pid": "14e39ab6ebd54fe88ab46ebf567f728c",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "BALANCE_BILL_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "ce44a33c3f3847a09ddd869d6135748c",
    "inputTime": "2020-04-10 15:11:59",
    "name": "编辑",
    "pid": "14e39ab6ebd54fe88ab46ebf567f728c",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "BALANCE_BILL_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "bdbfbd0c1ace480ba80af726a3772d04",
    "inputTime": "2020-03-13 11:37:39",
    "name": "账户概览",
    "pid": "98d56736c32d4ed4a20cb93b1335e7bb",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "BALANCE_ACCOUNT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "58e413c517e340e58471387fee0b5dc2",
    "inputTime": "2020-03-13 11:37:39",
    "name": "提现",
    "pid": "bdbfbd0c1ace480ba80af726a3772d04",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "BALANCE_ACCOUNT_WITHDRAW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "dc4d8ca30d3b4195be4441ed99c9b972",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "bdbfbd0c1ace480ba80af726a3772d04",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "BALANCE_ACCOUNT_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "c5aed92064ad408482a81f308e08caf3",
    "inputTime": "2020-03-13 11:37:39",
    "name": "店铺余额",
    "pid": "98d56736c32d4ed4a20cb93b1335e7bb",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "BALANCE_STORE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "101fd7c9342d462ca9c2caa065ff9d0f",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "c5aed92064ad408482a81f308e08caf3",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "BALANCE_STORE_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "53ab024e7f1741f6adcdeed7d38eaddb",
    "inputTime": "2020-03-13 11:37:39",
    "name": "提现",
    "pid": "c5aed92064ad408482a81f308e08caf3",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "BALANCE_STORE_WITHDRAW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "af3d0599f47d40519761b8b8e907fa3b",
    "inputTime": "2020-03-13 11:37:38",
    "name": "订单",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "ORDER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "04dfe871c01e42359baa15db43f14f7c",
    "inputTime": "2020-03-13 11:37:38",
    "name": "运费模板",
    "pid": "af3d0599f47d40519761b8b8e907fa3b",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "ORDER_FREIGHT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "35f6af50232e4c99911eb2b96bb36f53",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "04dfe871c01e42359baa15db43f14f7c",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_FREIGHT_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "4f03a1c7706047e3a5bebb8ce46f50b5",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "04dfe871c01e42359baa15db43f14f7c",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_FREIGHT_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "37708830d0ba4bd1b764150638306938",
    "inputTime": "2020-03-13 11:37:38",
    "name": "核销管理",
    "pid": "af3d0599f47d40519761b8b8e907fa3b",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "ORDER_CHECK",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "ae2d54fc592147f9a5777aebc35ea1ed",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "37708830d0ba4bd1b764150638306938",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_CHECK_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "b9d5844d82be4205ac269b0a8fe50848",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "37708830d0ba4bd1b764150638306938",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_CHECK_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "847a18ddfe0e47d4853225687494e0b9",
    "inputTime": "2020-03-13 11:37:38",
    "name": "订单管理",
    "pid": "af3d0599f47d40519761b8b8e907fa3b",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "ORDER_MANAGER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "2e4c93c663fb4c7b87624604d874176e",
    "inputTime": "2020-03-13 11:37:38",
    "name": "取消订单",
    "pid": "847a18ddfe0e47d4853225687494e0b9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_MANAGER_CANCER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "33558c26e94745c2a8fdbe1e67676f36",
    "inputTime": "2020-03-13 11:37:38",
    "name": "主动退款",
    "pid": "847a18ddfe0e47d4853225687494e0b9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_MANAGER_REFUND",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "99a7083afdd44097976933b7e7f7e9d0",
    "inputTime": "2020-03-13 11:37:38",
    "name": "修改价格",
    "pid": "847a18ddfe0e47d4853225687494e0b9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_MANAGER_CHANGE_PRICE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "adedb30bee1d4050a278902f7ce71490",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "847a18ddfe0e47d4853225687494e0b9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_MANAGER_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "d925cd5b23684bf9a8964e01c7d32aef",
    "inputTime": "2020-03-13 11:37:38",
    "name": "备注",
    "pid": "847a18ddfe0e47d4853225687494e0b9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_MANAGER_REMARK",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "e4180663565648d387ef7ec210902092",
    "inputTime": "2020-03-13 11:37:38",
    "name": "发货",
    "pid": "847a18ddfe0e47d4853225687494e0b9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_MANAGER_DELIVER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "f08a4b7f97e04cb887b7e917eeabfbfd",
    "inputTime": "2020-03-13 11:37:38",
    "name": "退款管理",
    "pid": "af3d0599f47d40519761b8b8e907fa3b",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "ORDER_REFUND",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "4c983c75a2654e63840db23cb2db0b14",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "f08a4b7f97e04cb887b7e917eeabfbfd",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_REFUND_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "67f7e5adcd9f447dac9defd69a7f0b11",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "f08a4b7f97e04cb887b7e917eeabfbfd",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "ORDER_REFUND_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "cb84ee5405c745b19a1630ba6f7dea86",
    "inputTime": "2020-03-13 11:37:38",
    "name": "促销",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "SALE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "5ef9f0b799254f129fb3199dd330e75e",
    "inputTime": "2020-03-13 11:37:38",
    "name": "优惠券",
    "pid": "cb84ee5405c745b19a1630ba6f7dea86",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SALE_COUPON",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "29de633bea674fc8a032eba55f16f11b",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "5ef9f0b799254f129fb3199dd330e75e",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SALE_COUPON_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "70cf4d0525b144acb38c02e4ca975a00",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "5ef9f0b799254f129fb3199dd330e75e",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SALE_COUPON_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "a7042e83f5914c5ea893adb96d97ddec",
    "inputTime": "2020-03-13 11:37:38",
    "name": "店铺促销",
    "pid": "cb84ee5405c745b19a1630ba6f7dea86",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SALE_STORE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "4118da2846a24f608c8c1e5101ad9106",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "a7042e83f5914c5ea893adb96d97ddec",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SALE_STORE_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "ee65c6e9d0c846d2b96feefae14344fe",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "a7042e83f5914c5ea893adb96d97ddec",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SALE_STORE_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "d67835b2b7f8483eaa2568bc1563b54d",
    "inputTime": "2020-03-13 11:37:38",
    "name": "促销审核",
    "pid": "cb84ee5405c745b19a1630ba6f7dea86",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "SALE_AUTH",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "95a6ed7741d4438796b8c0889bc9f285",
    "inputTime": "2020-03-13 11:37:39",
    "name": "编辑",
    "pid": "d67835b2b7f8483eaa2568bc1563b54d",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SALE_AUTH_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "ef7ae50efe76443f8b4a7a2cb057c000",
    "inputTime": "2020-03-13 11:37:39",
    "name": "查看",
    "pid": "d67835b2b7f8483eaa2568bc1563b54d",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "SALE_AUTH_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "d96ad041fe174a7794485c568f1c19c0",
    "inputTime": "2020-03-13 11:37:38",
    "name": "数据",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "DATA",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "67442960509b48b9ae81bac110f9e685",
    "inputTime": "2020-03-13 11:37:38",
    "name": "商品分析",
    "pid": "d96ad041fe174a7794485c568f1c19c0",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "DATA_GOODS",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "90f00969b7ae4c9ba176165a13ed790b",
    "inputTime": "2020-03-13 11:37:38",
    "name": "优惠券分析",
    "pid": "d96ad041fe174a7794485c568f1c19c0",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "DATA_SALE",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "9a21376a8cac4da49399c26c81296025",
    "inputTime": "2020-03-13 11:37:38",
    "name": "数据概览",
    "pid": "d96ad041fe174a7794485c568f1c19c0",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "DATA_INDEX",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "db82c5509f1c4fb1a104a178ef4235a7",
    "inputTime": "2020-03-13 11:37:38",
    "name": "流量分析",
    "pid": "d96ad041fe174a7794485c568f1c19c0",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "DATA_FLOW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "dd893ae2870a4b69a65d1d01cabb9218",
    "inputTime": "2020-03-13 11:37:38",
    "name": "商品",
    "pid": "0",
    "remark": "",
    "type": 0,
    "updateTime": null,
    "value": "GOODS",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "20984bae8024413b93f06eddfb21a914",
    "inputTime": "2020-03-13 11:37:38",
    "name": "商品分组",
    "pid": "dd893ae2870a4b69a65d1d01cabb9218",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "GOODS_GROUPS",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "60bc2d6004614818babb08345d92e559",
    "inputTime": "2020-04-10 15:00:14",
    "name": "查看",
    "pid": "20984bae8024413b93f06eddfb21a914",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "GOODS_GROUPS_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "7655adf9c28a4d9f93a8cc4ea7bb5ae2",
    "inputTime": "2020-04-10 15:00:14",
    "name": "编辑",
    "pid": "20984bae8024413b93f06eddfb21a914",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "GOODS_GROUPS_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "2724abbfd348400f9cd2b1b6e1770324",
    "inputTime": "2020-03-13 11:37:38",
    "name": "商品标签",
    "pid": "dd893ae2870a4b69a65d1d01cabb9218",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "GOODS_LABEL",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "8b60007b76574b7eae6971cc52b39d63",
    "inputTime": "2020-04-10 15:00:14",
    "name": "编辑",
    "pid": "2724abbfd348400f9cd2b1b6e1770324",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "GOODS_LABEL_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "dd4705dd9b084b42ba98471336039e2b",
    "inputTime": "2020-04-10 15:00:14",
    "name": "查看",
    "pid": "2724abbfd348400f9cd2b1b6e1770324",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "GOODS_LABEL_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "afd29571e02846db8319ffad7ed959c9",
    "inputTime": "2020-03-13 11:37:38",
    "name": "商品管理",
    "pid": "dd893ae2870a4b69a65d1d01cabb9218",
    "remark": "",
    "type": 1,
    "updateTime": null,
    "value": "GOODS_MANAGER",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "6634292efaf64904a36909fe4cf674a4",
    "inputTime": "2020-03-13 11:37:38",
    "name": "查看",
    "pid": "afd29571e02846db8319ffad7ed959c9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "GOODS_MANAGER_VIEW",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    },
    {
    "children": [],
    "id": "a04ae0e5602a4e7e80af685316ac7441",
    "inputTime": "2020-03-13 11:37:38",
    "name": "编辑",
    "pid": "afd29571e02846db8319ffad7ed959c9",
    "remark": "",
    "type": 2,
    "updateTime": null,
    "value": "GOODS_MANAGER_EDIT",
    "desc": "String id【ID】String name【权限名称】String value【权限值】Integer type【权限类型：0：菜单，1：页面，2：按钮】String remark【备注】String pid【父ID】String inputAcc【录入人】Date inputTime【录入时间】String updateAcc【更新人】Date updateTime【更新时间】Integer isDel【是否删除 1:删除,0:未删除】List children【是否删除 1:删除,0:未删除】String searchText【模糊搜索文本】List queryDateArr【时间查询数组】String querySql【查询sql】"
    }
];

export default permissionList;