const hasPermission = (value, permissionList) => {
    const permissions = permissionList && permissionList.length > 0 
        ? permissionList
        : (
            (JSON.parse(sessionStorage.getItem('userInfo')) || {}).permissions || []
        )
    // const permissions = [
    //     "INDEX",
    //     "INDEX_VISIT_CHART",
    //     "INDEX_SHORTCUT",
    //     "INDEX_SHORTCUT_ORDER_QUERY",
    //     "INDEX_SHORTCUT_CUSTOMER_MANAGER",
    //     "INDEX_SHORTCUT_INCOME",
    //     "INDEX_SHORTCUT_NEW_GOODS",
    //     "INDEX_DEAL_CHART",
    //     "INDEX_BANNER",
    //     "CUSTOMER",
    //     "CUSTOMER_MANAGER",
    //     "CUSTOMER_MANAGER_EDIT",
    //     "CUSTOMER_MANAGER_VIEW",
    //     "CUSTOMER_LABEL",
    //     "CUSTOMER_LABEL_VIEW",
    //     "CUSTOMER_LABEL_EDIT",
    //     "SET",
    //     "SET_COMMON",
    //     "SET_COMMON_VIEW",
    //     "SET_COMMON_EDIT",
    //     "SET_STORE",
    //     "SET_STORE_VIEW",
    //     "SET_STORE_EDIT",
    //     "SET_USER",
    //     "SET_USER_EDIT",
    //     "SET_USER_VIEW",
    //     "SET_ADDRESS",
    //     "SET_ADDRESS_VIEW",
    //     "SET_ADDRESS_EDIT",
    //     "SET_ROLE",
    //     // "SET_ROLE_EDIT",
    //     "SET_ROLE_VIEW",
    //     "SET_CHECKER",
    //     "SET_CHECKER_EDIT",
    //     "SET_CHECKER_VIEW",
    //     "BALANCE",
    //     "BALANCE_BILL",
    //     "BALANCE_BILL_VIEW",
    //     "BALANCE_BILL_EDIT",
    //     "BALANCE_ACCOUNT",
    //     "BALANCE_ACCOUNT_WITHDRAW",
    //     "BALANCE_ACCOUNT_VIEW",
    //     "BALANCE_STORE",
    //     "BALANCE_STORE_VIEW",
    //     "BALANCE_STORE_WITHDRAW",
    //     "ORDER",
    //     "ORDER_FREIGHT",
    //     "ORDER_FREIGHT_VIEW",
    //     "ORDER_FREIGHT_EDIT",
    //     "ORDER_CHECK",
    //     "ORDER_CHECK_EDIT",
    //     "ORDER_CHECK_VIEW",
    //     "ORDER_MANAGER",
    //     "ORDER_MANAGER_CANCER",
    //     "ORDER_MANAGER_REFUND",
    //     "ORDER_MANAGER_CHANGE_PRICE",
    //     "ORDER_MANAGER_VIEW",
    //     "ORDER_MANAGER_REMARK",
    //     "ORDER_MANAGER_DELIVER",
    //     "ORDER_REFUND",
    //     "ORDER_REFUND_EDIT",
    //     "ORDER_REFUND_VIEW",
    //     "SALE",
    //     "SALE_COUPON",
    //     "SALE_COUPON_EDIT",
    //     "SALE_COUPON_VIEW",
    //     "SALE_STORE",
    //     "SALE_STORE_VIEW",
    //     "SALE_STORE_EDIT", 
    //     "SALE_AUTH",
    //     "SALE_AUTH_EDIT",
    //     "SALE_AUTH_VIEW",
    //     "DATA",
    //     "DATA_GOODS",
    //     "DATA_SALE",
    //     "DATA_INDEX",
    //     "DATA_FLOW",
    //     "GOODS",
    //     "GOODS_GROUPS",
    //     "GOODS_GROUPS_VIEW",
    //     "GOODS_GROUPS_EDIT",
    //     "GOODS_LABEL",
    //     "GOODS_LABEL_EDIT",
    //     "GOODS_LABEL_VIEW",
    //     "GOODS_MANAGER",
    //     "GOODS_MANAGER_VIEW",
    //     "GOODS_MANAGER_EDIT"

    // ]
    // console.log(value, permissions, permissions.includes(value))
    return permissions.includes(value)
}

export default {
    hasPermission
}